/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VICTOR MANUEL ARANDA
 */
public class jp_usuarios extends javax.swing.JPanel {

    /**
     * Creates new form jp_usuarios
     */
    public jp_usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jp_usuarios = new javax.swing.JPanel();
        jl_user_name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_datos_usr = new javax.swing.JTable();
        jtf_user_name = new javax.swing.JTextField();
        jp_button_prov = new javax.swing.JPanel();
        jb_nuevo_user = new javax.swing.JButton();
        jb_actualizar_user = new javax.swing.JButton();
        jb_borrar_user = new javax.swing.JButton();
        jb_guardar_user = new javax.swing.JButton();
        jb_cancelar_user = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jp_usuarios.setBackground(new java.awt.Color(0, 102, 102));
        jp_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_user_name.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jl_user_name.setText("Nombre de Usuario:");
        jp_usuarios.add(jl_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));

        jt_datos_usr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jt_datos_usr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_datos_usrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_datos_usr);

        jp_usuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 100));
        jp_usuarios.add(jtf_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 87, -1));

        jp_button_prov.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_nuevo_user.setBackground(new java.awt.Color(153, 153, 153));
        jb_nuevo_user.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_nuevo_user.setForeground(new java.awt.Color(51, 51, 51));
        jb_nuevo_user.setText("Nuevo");
        jb_nuevo_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_nuevo_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jb_actualizar_user.setBackground(new java.awt.Color(153, 153, 153));
        jb_actualizar_user.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_actualizar_user.setForeground(new java.awt.Color(51, 51, 51));
        jb_actualizar_user.setText("Actualizar");
        jb_actualizar_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_actualizar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jb_borrar_user.setBackground(new java.awt.Color(153, 153, 153));
        jb_borrar_user.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_borrar_user.setForeground(new java.awt.Color(51, 51, 51));
        jb_borrar_user.setText("Borrar");
        jb_borrar_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_borrar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jb_guardar_user.setBackground(new java.awt.Color(153, 153, 153));
        jb_guardar_user.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_guardar_user.setForeground(new java.awt.Color(51, 51, 51));
        jb_guardar_user.setText("Guardar");
        jb_guardar_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_guardar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jb_cancelar_user.setBackground(new java.awt.Color(255, 0, 0));
        jb_cancelar_user.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_cancelar_user.setForeground(new java.awt.Color(51, 51, 51));
        jb_cancelar_user.setText("Cancelar");
        jb_cancelar_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_cancelar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_top_img.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jp_button_prov.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -6, 290, 110));

        jp_usuarios.add(jp_button_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_slider.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jp_usuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_datos_usrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_datos_usrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_datos_usrMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_actualizar_user;
    private javax.swing.JButton jb_borrar_user;
    private javax.swing.JButton jb_cancelar_user;
    private javax.swing.JButton jb_guardar_user;
    private javax.swing.JButton jb_nuevo_user;
    private javax.swing.JLabel jl_user_name;
    private javax.swing.JPanel jp_button_prov;
    private javax.swing.JPanel jp_usuarios;
    private javax.swing.JTable jt_datos_usr;
    private javax.swing.JTextField jtf_user_name;
    // End of variables declaration//GEN-END:variables
}
