
public class jp_ventas extends javax.swing.JPanel {

  
    public jp_ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_ventas = new javax.swing.JPanel();
        jl_folio = new javax.swing.JLabel();
        jl_producto_venta = new javax.swing.JLabel();
        jtf_folio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_datos_vnt = new javax.swing.JTable();
        jp_button_prov = new javax.swing.JPanel();
        jb_nuevo_prove = new javax.swing.JButton();
        jb_actualizar_prove = new javax.swing.JButton();
        jb_borrar_prove = new javax.swing.JButton();
        jb_guardar_prove = new javax.swing.JButton();
        jb_cancelar_prove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtf_producto_venta = new javax.swing.JTextField();
        jl_precio = new javax.swing.JLabel();
        jl_existencia = new javax.swing.JLabel();
        jtf_existencia = new javax.swing.JTextField();
        jtf_precio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jp_ventas.setBackground(new java.awt.Color(0, 102, 102));
        jp_ventas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_folio.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jl_folio.setText("Folio");
        jp_ventas.add(jl_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        jl_producto_venta.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jl_producto_venta.setText("Producto");
        jp_ventas.add(jl_producto_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 20));
        jp_ventas.add(jtf_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 87, -1));

        jt_datos_vnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jt_datos_vnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_datos_vntMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_datos_vnt);

        jp_ventas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 100));

        jp_button_prov.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_nuevo_prove.setBackground(new java.awt.Color(153, 153, 153));
        jb_nuevo_prove.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_nuevo_prove.setForeground(new java.awt.Color(51, 51, 51));
        jb_nuevo_prove.setText("Nuevo");
        jb_nuevo_prove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_nuevo_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jb_actualizar_prove.setBackground(new java.awt.Color(153, 153, 153));
        jb_actualizar_prove.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_actualizar_prove.setForeground(new java.awt.Color(51, 51, 51));
        jb_actualizar_prove.setText("Actualizar");
        jb_actualizar_prove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_actualizar_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jb_borrar_prove.setBackground(new java.awt.Color(153, 153, 153));
        jb_borrar_prove.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_borrar_prove.setForeground(new java.awt.Color(51, 51, 51));
        jb_borrar_prove.setText("Borrar");
        jb_borrar_prove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_borrar_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jb_guardar_prove.setBackground(new java.awt.Color(153, 153, 153));
        jb_guardar_prove.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_guardar_prove.setForeground(new java.awt.Color(51, 51, 51));
        jb_guardar_prove.setText("Guardar");
        jb_guardar_prove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_guardar_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jb_cancelar_prove.setBackground(new java.awt.Color(255, 0, 0));
        jb_cancelar_prove.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jb_cancelar_prove.setForeground(new java.awt.Color(51, 51, 51));
        jb_cancelar_prove.setText("Cancelar");
        jb_cancelar_prove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_button_prov.add(jb_cancelar_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_top_img.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jp_button_prov.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 270, 100));

        jp_ventas.add(jp_button_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 80));
        jp_ventas.add(jtf_producto_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 87, -1));

        jl_precio.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jl_precio.setText("Precio");
        jp_ventas.add(jl_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 20));

        jl_existencia.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jl_existencia.setText("Existencia");
        jp_ventas.add(jl_existencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));
        jp_ventas.add(jtf_existencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 87, -1));
        jp_ventas.add(jtf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 87, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_slider.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jp_ventas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_datos_vntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_datos_vntMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_datos_vntMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_actualizar_prove;
    private javax.swing.JButton jb_borrar_prove;
    private javax.swing.JButton jb_cancelar_prove;
    private javax.swing.JButton jb_guardar_prove;
    private javax.swing.JButton jb_nuevo_prove;
    private javax.swing.JLabel jl_existencia;
    private javax.swing.JLabel jl_folio;
    private javax.swing.JLabel jl_precio;
    private javax.swing.JLabel jl_producto_venta;
    private javax.swing.JPanel jp_button_prov;
    private javax.swing.JPanel jp_ventas;
    private javax.swing.JTable jt_datos_vnt;
    private javax.swing.JTextField jtf_existencia;
    private javax.swing.JTextField jtf_folio;
    private javax.swing.JTextField jtf_precio;
    private javax.swing.JTextField jtf_producto_venta;
    // End of variables declaration//GEN-END:variables
}
